# Script: Build docker image
simulate:
    only:
        - master
        - tags

    script:
        # Update current system
        - apt -y update && apt -y upgrade

        # Install latest version of ModelSim
        - dpkg --add-architecture i386
        - apt update
        - apt install -y libc6:i386 libxtst6:i386 libncurses5:i386 libxft2:i386 libstdc++6:i386 libc6-dev-i386 lib32z1 libqt5xml5 liblzma-dev
        - wget https://download.altera.com/akdlm/software/acdsinst/20.1std/711/ib_installers/ModelSimSetup-20.1.0.711-linux.run
        - chmod +x ModelSimSetup-20.1.0.711-linux.run
        - ./ModelSimSetup-20.1.0.711-linux.run --mode unattended --accept_eula 1 --installdir $HOME/ModelSim-20.1.0 --unattendedmodeui none
        - export PATH="$HOME/ModelSim-20.1.0/modelsim_ase/bin:$PATH"

        # Install cocotb stuff
        - apt -y install python3 python3-pip
        - pip3 install cocotb cocotbext-axi cocotbext-uart cocotb-test

        # Run simulation
        - cd ./tb
        - make
