# Script: Build docker image
simulate:
    only:
        - master
        - tags

    script:
        # Update current system
        - apt -y update && apt -y upgrade

        # Install latest version of Icarus Verilog
        - apt -y install autoconf gperf flex bison build-essential
        - git clone https://github.com/steveicarus/iverilog.git
        - cd iverilog
        - git checkout --track -b v11-branch origin/v11-branch
        - git pull
        - sh autoconf.sh
        - ./configure
        - make
        - make install
        - cd ./../

        # Install cocotb stuff
        - apt -y install python3 python3-pip
        - pip3 install cocotb cocotbext-axi cocotbext-uart cocotb-test

        # Run simulation
        - cd ./tb
        - make WAVES=1
